### PR TITLE
Fix INTERNALERROR when an xdist slave crashes.

### LINKED ISSUE #21: AttributeError: 'SlaveController' object has no attribute 'slaveoutput'
I got this weird error with 1.6:
```
Traceback (most recent call last):
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/main.py", line 84, in wrap_session
    doit(config, session)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/main.py", line 122, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/xdist/dsession.py", line 521, in pytest_runtestloop
    self.loop_once()
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/xdist/dsession.py", line 539, in loop_once
    call(**kwargs)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/xdist/dsession.py", line 582, in slave_errordown
    self.config.hook.pytest_testnodedown(node=node, error=error)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/var/lib/jenkins/virtenv/428e316eff82784c964740c18463dd91/lib/python2.7/site-packages/pytest_html/plugin.py", line 61, in pytest_testnodedown
    node.config._environment = node.slaveoutput['environment']
AttributeError: 'SlaveController' object has no attribute 'slaveoutput'

```

Any idea what's going on?

### PR DESCRIPTION
**Pull request by The-Compiler**
Fixes #21.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
please issue a pytest-warning in case of a failed node

**Comment by davehunt** [comment]
I've reverted this because it fails when running with pytest 2.8.2

**Comment by ionelmc** [comment]
Any details about how this fails on 2.8/2.x?

**Comment by The-Compiler** [comment]
Seems like it produces a lot of errors with Python 2.6: https://travis-ci.org/davehunt/pytest-html/jobs/86139950

And just hangs with 2.7: https://travis-ci.org/davehunt/pytest-html/jobs/86139950

It works fine with older pytest or newer Python versions: https://travis-ci.org/davehunt/pytest-html/builds/86139938

**Comment by davehunt** [comment]
For now I've relanded and xfailed this test on the affected versions.

**Pull request merged**
